version: 2
jobs:
  build:
    docker:
      - image: vvakame/review:2.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: sass install
          command: gem install sass -v "3.4.25"
      - run:
          name: Setup
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Build PDF
          command: npm run pdf
      - store_artifacts:
          path: ./articles/NefryBook.pdf
          destination: NefryBook.pdf
      - run:
          name: chmod permissions
          command: chmod +x ./ReViewDeploy.sh
      - add_ssh_keys:
          fingerprints:
            - "bb:7f:a7:d1:fb:9e:c0:39:fc:cd:f1:b8:28:e7:0d:44"
      - run:
          name: Upload to Document
          command: ./ReViewDeploy.sh
